version: '3'
services:
  app: 
    build: 
      context: .       
    ports:
      - 8000:8000
    volumes:
      - ./app:/app  
    command: npm run watch  

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
     

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
   

volumes:
  mongodata:
    driver: local
      

